config/routes.rb
Rails.application.routes.draw do
  root 'urls#index'
  resources :urls
  get '*url_short' => 'urls#redirect_to_long_url'
end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :urlLong, presence: true
  after_create :convert_short

  def convert_short
    self.update_attribute(:urlShort, SecureRandom.hex(6))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
		@urls = Url.all
	end

	def show
	    @url = Url.find(params[:id])
	end

	def new
	    @url = Url.new
	end

  def create
    @url = Url.new(url_params)
    if @url.save
      redirect_to @url
    else
      render 'new'
    end
  end

  def redirect_to_long_url
    @url = Url.find_by(urlShort: params[:url_short])
    redirect_to @url.urlLong
  end

	private

	def url_params
	    params.require(:url).permit(:urlLong, :urlShort)
	end
end

app/views/urls/_form.html.erb
<%= form_for @url do |f| %>

  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@url.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @url.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.text_field :urlLong %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/urls/index.html.erb
<h1>Listing Urls</h1>
<h2>Bold characters are the endpoints (short urls) just use it as:</h2>
<h3>localhost:3000/*your_endpoint*</h3>
<%= link_to 'New url', new_url_path %>
<table>
  <tr>
    <th>Long Urls</th>
    <th colspan="2"></th>
  </tr>

  <% @urls.each do |url| %>
    <tr>
      <td><%= url.urlLong %></td>
      <td style="font-weight:bold"><%= url.urlShort %></td>
    </tr>
  <% end %>
</table>

app/views/urls/new.html.erb
<h1>New URL</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p>
  <strong>Long Url:</strong>
  <%= @url.urlLong %>
</p>

<p>
  <strong>Short Url:</strong>
  <%= @url.urlShort %>
</p>

<%= link_to 'Back', urls_path %>